export const LOGIN_FAIL="LOGIN_FAIL"
export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"


export const LOAD_PROFILE="LOAD_PROFILE"
export const LOG_OUT="LOG_OUT"



export const SEARCH_VIDEO_FAIL="SEARCH_VIDEO_FAIL"
export const SEARCH_VIDEO_REQUEST="SEARCH_VIDEO_REQUEST"
export const SEARCH_VIDEO_SUCCESS="SELECTED_VIDEO_SUCCESS"


export const VIDEO_DETAILS_FAIL="VIDEO_DETAILS_FAIL"
export const VIDEO_DETAILS_REQUEST="VIDEO_DETAILS_REQUEST"
export const VIDEO_DETAILS_SUCCESS="VIDEO_DETAILS_SUCCESS"


export const RELATED_VIDEO_FAIL="RELATED_VIDEO_FAIL"
export const RELATED_VIDEO_REQUEST="RELATED_VIDEO_REQUEST"
export const RELATED_VIDEO_SUCCESS="RELATED_VIDEO_SUCCESS"


export const CHANNEL_VIDEO_FAIL="CHANNEL_VIDEO_FAIL"
export const CHANNEL_VIDEO_REQUEST="CHANNEL_VIDEO_REQUEST"
export const CHANNEL_VIDEO_SUCCESS="CHANNEL_VIDEO_SUCCESS"



export const COMMENT_LIST_FAIL="COMMENT_LIST_FAIL"
export const COMMENT_LIST_REQUEST="COMMENT_LIST_REQUEST"
export const COMMENT_LIST_SUCCESS="COMMENT_LIST_SUCCESS"


export const SHORT_LIST_FAIL="SHORT_LIST_FAIL"
export const SHORT_LIST_REQUEST="SHORT_LIST_REQUEST"
export const SHORT_LIST_SUCCESS="SHORT_LIST_SUCCESS"

export const CHANNEL_ID_FAIL="CHANNEL_ID_FAIL"
export const CHANNEL_ID_REQUEST="CHANNEL_ID_REQUEST"
export const CHANNEL_ID_SUCCESS="CHANNEL_ID_SUCCESS"



